data archival application/objects/DataArchive__b.object
<CustomObject>
    <fields>
        <fullName>DateTimeStampIndex__c</fullName>
        <label>DateTimeStamp Index</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordJson0__c</fullName>
        <label>RecordJson0</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson1__c</fullName>
        <label>RecordJson1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>indexNumber__c</fullName>
        <label>indexNumber</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DataArchive</label>
    <pluralLabel>DataArchives</pluralLabel>
</CustomObject>

data archival application/classes/ArchivalHelperControllerTest.cls
@isTest
public class ArchivalHelperControllerTest {
  
    @istest 
    public static void getSetupRequired1()
    {
        Map<String,Decimal> sobjectlist=new Map<String,Decimal>();
        DataArchive__b headerRec=new DataArchive__b (indexNumber__c=0,datetimestampindex__c='HeadersIndex',recordjson0__c=json.serialize(sobjectlist),recordJson1__c=json.serialize(sobjectlist));
        bigObjectQueryService.bigObjectQueryMap.put('select indexNumber__c,datetimestampindex__c,recordjson0__c,recordJson1__c from DataArchive__b where indexNumber__c=0 and datetimestampindex__c=\'HeadersIndex\'',new List<DataArchive__b>{headerRec}); 
        Test.startTest();
        ArchivalHelperController.getSetupRequired();
        ArchivalHelperController.createSetupForArchival();
        ArchivalHelperController.getReportingData();
        Test.stopTest();
    }
   
}