data migration assistant  (Package for Source Org)/objects/Data_Migration__b.object
<CustomObject>
    <fields>
        <fullName>DateTimeStampIndex__c</fullName>
        <label>DateTimeStampIndex</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>indexValue__c</fullName>
        <label>indexValue</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>targetOrg__c</fullName>
        <label>targetOrg</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Migration</label>
    <pluralLabel>Data Migrations</pluralLabel>
</CustomObject>

data migration assistant  (Package for Source Org)/classes/deleteBigObjectsBatch.cls
public class deleteBigObjectsBatch implements database.Batchable<data_migration__b> {
public Iterable<data_migration__b> start(Database.BatchableContext BC){
    List<data_migration__b> datamigrationList=[select indexValue__c,DateTimeStampIndex__c,targetOrg__c,Object__c from Data_Migration__b];
            return datamigrationList;
}

public void execute(Database.BatchableContext BC, List<data_migration__b> scope){
   database.deleteImmediate(scope);
}
public void finish(Database.BatchableContext BC){
      String Body='Report for data Migration is now available. Please check in the application';
        MetadataHandlerClass.sendmail('Migration Report settings reset',body);
}
}