Email Archival Application/objects/Archival_date__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_date__c</fullName>
        <label>To date</label>
        <type>DateTime</type>
    </fields>
    <label>Archival date</label>
</CustomObject>

Email Archival Application/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Email_Archive_Indexes__c</fullName>
        <label>Email Archive Indexes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

Email Archival Application/objects/EmailArchive__b.object
<CustomObject>
    <fields>
        <fullName>DateTimeStampIndex__c</fullName>
        <label>DateTimeStamp Index</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordJson0__c</fullName>
        <label>RecordJson0</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson10__c</fullName>
        <label>RecordJson10</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson11__c</fullName>
        <label>RecordJson11</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson1__c</fullName>
        <label>RecordJson1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson2__c</fullName>
        <label>RecordJson2</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson3__c</fullName>
        <label>RecordJson3</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson4__c</fullName>
        <label>RecordJson4</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson5__c</fullName>
        <label>RecordJson5</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson6__c</fullName>
        <label>RecordJson6</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson7__c</fullName>
        <label>RecordJson7</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson8__c</fullName>
        <label>RecordJson8</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordJson9__c</fullName>
        <label>RecordJson9</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>indexNumber__c</fullName>
        <label>indexNumber</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EmailArchive</label>
    <pluralLabel>EmailArchives</pluralLabel>
</CustomObject>

Email Archival Application/classes/emailUnarchivalLight.cls
public class emailUnarchivalLight {
    
    /* @AuraEnabled
public static Map<Integer,List<String>> unarchiveEmailMessages(Integer index){
List<String> emailList=new  List<String>();
//List<EmailArchive__b> emailArchiveList= ;
Integer newIndex;
system.debug('index' + index);
for(emailArchive__b emb:[select recordjson0__c,recordjson1__c,recordjson2__c,recordjson3__c,recordjson4__c,recordjson5__c,
recordjson6__c,recordjson7__c,recordjson8__c,recordjson9__c,recordjson10__c,recordjson11__c,DateTimeStampIndex__c,indexNumber__c from emailArchive__b where indexNumber__c>:index limit 1000]){
//system.debug(json.deserializeUntyped(emb.recordjson9__c));
system.debug('emb'+emb.indexNumber__c);
emailList.add(emb.recordjson0__c);
emailList.add(emb.recordjson1__c);
emailList.add(emb.recordjson2__c);
emailList.add(emb.recordjson3__c);
emailList.add(emb.recordjson4__c);
emailList.add(emb.recordjson5__c);
emailList.add(emb.recordjson6__c);
emailList.add(emb.recordjson7__c);
emailList.add(emb.recordjson8__c);
emailList.add(emb.recordjson9__c);
emailList.add(emb.recordjson10__c);
emailList.add(emb.recordjson11__c);
newIndex=emb.indexNumber__c.intValue();
}

Map<Integer,List<String>> emailMap= new Map<Integer,List<String>>();
system.debug(emailList.size());
if(emailList.size()>0){

emailMap.put(newIndex,emailList);
return emailMap;            
}      
else
return null;
}*/
     @AuraEnabled
    public static List<String> unarchiveEmailMessages(String caseNumber){
        List<String> emailList=new  List<String>();
        //List<EmailArchive__b> emailArchiveList= ;
        Case cs=[select id,Email_archive_indexes__c,casenumber from case where casenumber=:casenumber];
        List<Decimal> emailindex=new  List<Decimal>();
        for(String str:cs.Email_Archive_Indexes__c.split(';'))
            emailindex.add(Decimal.valueOf(str));
        List<EmailArchive__b> archList=new List<EmailArchive__b>();
        if(Test.isRunningTest()){
            archList.add(new EmailArchive__b(indexNumber__c=1,recordjson0__c='{}'));
        }
        else
            archList=[select recordjson0__c,recordjson1__c,recordjson2__c,recordjson3__c,recordjson4__c,recordjson5__c,recordjson6__c,recordjson7__c,recordjson8__c,recordjson9__c,recordjson10__c,recordjson11__c,DateTimeStampIndex__c,indexNumber__c from emailArchive__b where indexNumber__c IN :emailindex];
        
        for(emailArchive__b emb:archList){
            //system.debug(json.deserializeUntyped(emb.recordjson9__c));
            system.debug('emb'+emb.indexNumber__c);
            emailList.add(emb.recordjson0__c);
            emailList.add(emb.recordjson1__c);
            emailList.add(emb.recordjson2__c);
            emailList.add(emb.recordjson3__c);
            emailList.add(emb.recordjson4__c);
            emailList.add(emb.recordjson5__c);
            emailList.add(emb.recordjson6__c);
            emailList.add(emb.recordjson7__c);
            emailList.add(emb.recordjson8__c);
            emailList.add(emb.recordjson9__c);
            emailList.add(emb.recordjson10__c);
            emailList.add(emb.recordjson11__c);
        }
        
        system.debug(emailList.size());
        if(emailList.size()>0){
            
            return emailList;            
        }      
        else
            return null; 
    }
   
    @AuraEnabled
    public static void ArchiveEmailMessages(){
        database.executeBatch(new parentCaseIdBatch(),200);
    }
    @AuraEnabled
    public static Boolean getBatchStatus(){
        List<Archival_date__c> settingList= [select id,From_Date__c,Object_Name__c,Status__c,To_date__c from Archival_date__c where Name=:userinfo.getuserid() and (status__c='Running')];
        return settingList.isEmpty();
    }
}